version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  pre_commit:
    executor: python/default
    # docker:
    #   - image: cimg/python:3.9.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --with=dev
      - run: poetry run pre-commit run --all-files --verbose
  pytest:
    executor: python/default
    # docker:
    #   - image: cimg/python:3.9.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --with=dev
      - run: poetry run pytest -v mozilla_bitbar_devicepool
      - run: poetry run pytest --cov=mozilla_bitbar_devicepool

workflows:
  main_test:
    jobs:
      - pre_commit
      - pytest
