version: 2.1

jobs:
  pre_commit:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            poetry --version
      - run: poetry install --with=dev
      - run: poetry run pre-commit run --all-files --verbose
  pytest:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            poetry --version
      - run: poetry install --with=dev
      - run: pytest -v mozilla_bitbar_devicepool
      - run: pytest --cov=mozilla_bitbar_devicepool

workflows:
  main_test:
    jobs:
      - pre_commit
      - pytest
