version: 2.1

jobs:
  pre_commit:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run: pre-commit run --all-files --verbose
  pytest:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest -v mozilla_bitbar_devicepool

workflows:
  ci_test:
    jobs:
      - pre_commit
      - pytest
