projects:
  defaults:
    os_type: ANDROID
    project_type: APPIUM_ANDROID_SERVER_SIDE
    application_file: relops-testdroid-sample-app.apk
    test_file: relops-empty-test.zip
    timeout: 0
    scheduler: SINGLE
    archivingStrategy: DAYS
    archivingItemCount: 7
    taskcluster_provisioner_id: proj-autophone
    additional_parameters:
      bitbar_cloud_url: https://mozilla.testdroid.com
      DOCKER_IMAGE_VERSION: 20231106T174322
      TC_WORKER_CONF: gecko-t-ap
  # generic-worker
  # mozilla-gw-unittest-p2:
  #   device_group_name: pixel2-unit-2
  #   device_model: pixel2
  #   framework_name: mozilla-usb
  #   description: Mozilla Unit tests for Pixel2 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-p2
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-p2
  # mozilla-gw-perftest-p2:
  #   device_group_name: pixel2-perf-2
  #   device_model: pixel2
  #   framework_name: mozilla-usb
  #   description: Mozilla Performance tests for Pixel2 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-p2
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-p2
  mozilla-gw-unittest-p5:
    device_group_name: pixel5-unit
    device_model: pixel5
    framework_name: mozilla-usb
    description: Mozilla Unit tests for Pixel5 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-p5
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-p5
  mozilla-gw-perftest-p5:
    device_group_name: pixel5-perf
    device_model: pixel5
    framework_name: mozilla-usb
    description: Mozilla Performance tests for Pixel5 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-p5
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-p5
  mozilla-gw-unittest-p6:
    device_group_name: pixel6-unit
    device_model: pixel6
    framework_name: mozilla-usb
    description: Mozilla Unit tests for Pixel6 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-p6
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-p6
  mozilla-gw-perftest-p6:
    device_group_name: pixel6-perf
    device_model: pixel6
    framework_name: mozilla-usb
    description: Mozilla Performance tests for Pixel6 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-p6
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-p6
  mozilla-gw-unittest-s21:
      device_group_name: s21-unit
      device_model: s21
      framework_name: mozilla-usb
      description: Mozilla Unit tests for Samsung Galaxy S21 (using generic-worker)
      additional_parameters:
        TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-s21
        TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-s21
  mozilla-gw-perftest-s21:
      device_group_name: s21-perf
      device_model: s21
      framework_name: mozilla-usb
      description: Mozilla Performance tests for Samsung Galaxy S21 (using generic-worker)
      additional_parameters:
        TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-s21
        TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-s21
  # mozilla-gw-perftest-g5:
  #   device_group_name: motog5-perf-2
  #   device_model: motog5
  #   framework_name: mozilla-usb
  #   description: Mozilla Performance tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-g5
  # mozilla-gw-batttest-p2:
  #   device_group_name: pixel2-batt-2
  #   device_model: pixel2
  #   framework_name: mozilla-tcp
  #   description: Mozilla Battery tests for Pixel2 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-batt-p2
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-batt-p2
  # mozilla-gw-batttest-g5:
  #   device_group_name: motog5-batt-2
  #   device_model: motog5
  #   framework_name: mozilla-tcp
  #   description: Mozilla Battery tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-batt-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-batt-g5
  # mozilla-gw-unittest-g5:
  #   device_group_name: motog5-unit-2
  #   device_model: motog5
  #   framework_name: mozilla-usb
  #   description: Mozilla Unit tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-g5
  # mozilla-gw-unittest-s7:
  #   device_group_name: s7-unit
  #   device_model: s7
  #   framework_name: mozilla-usb
  #   description: Mozilla Unit tests for S7Galaxy (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-s7
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-s7
  # mozilla-gw-perftest-s7:
  #   device_group_name: s7-perf
  #   device_model: s7
  #   framework_name: mozilla-usb
  #   description: Mozilla Performance tests for S7Galaxy (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-s7
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-s7
  mozilla-gw-unittest-a51:
    device_group_name: a51-unit
    device_model: a51
    framework_name: mozilla-usb
    description: Mozilla Unit tests for A51 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-a51
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-a51
  mozilla-gw-perftest-a51:
    device_group_name: a51-perf
    device_model: a51
    framework_name: mozilla-usb
    description: Mozilla Performance tests for A51 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-a51
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-a51
  # used for building new docker images
  # mozilla-docker-build:
  #   device_group_name: motog4-docker-builder-2
  #   device_model: motog4
  #   framework_name: Docker image build
  #   description: Mozilla Docker image build
  #   test_file: mozilla-docker-20240305T164354.zip
  #   # app file is defaulted
  #   additional_parameters:
  #     DOCKER_IMAGE_VERSION: 20240305T164354
  # used for testing new docker images
  mozilla-gw-test-1:
    device_group_name: test-1
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-1
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-1
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20231106T174322
  mozilla-gw-test-2:
    device_group_name: test-2
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-2
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-2
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20240305T164354
  mozilla-gw-test-3:
    device_group_name: test-3
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-3
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-3
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20231106T174322
  # mozilla-docker-image-test:
  #   device_group_name: motog5-test
  #   framework_name: mozilla-usb
  #   description: Mozilla Docker image test
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-test-g5
  #     # replace with version to test
  #     DOCKER_IMAGE_VERSION: 20200326T142021
# devices hooked up to battery hubs
#   - pixel2-34, pixel2-35. motog5-08, motog5-15.
device_groups:
  motog4-docker-builder-2:
    Docker Builder:
  test-1:
    # motog5-38:  # 11/30/22: disabling all g5, not used any longer
    #
    # testing android 13
    a51-02:  # running android 13
  test-2:
    # motog5-40:  # disabled due to a51 device increases (3/29/22)
    # testing new image 20240305T164354
    a51-01:
  test-3:
    # pixel2-60 has android 9.0 on it
    #pixel2-60: ## pulled 4/26/22
  a51-unit:
  a51-perf:
      a51-03:
      a51-04:
      a51-05:
      a51-06:
      a51-07:
      a51-08:
      a51-09:
      a51-10:
      a51-11:
      a51-12:
      a51-13:
      a51-14:
      a51-15:
      a51-16:
      a51-17:
      a51-18:
      a51-19:
      a51-20:
      a51-21:
      a51-22:
      a51-23:
      a51-24:
      a51-25:
      a51-26:
      a51-27:
      a51-28:
      a51-29:
      a51-30:
      a51-31:
      a51-32:
      a51-33:
      a51-34:
      a51-35:
      a51-36:
      a51-37:
      a51-38:
      a51-39:
      a51-40:
  pixel5-unit:
      pixel5-01:
      pixel5-02:
      pixel5-03:
      pixel5-04:
      pixel5-05:
      pixel5-06:
      pixel5-07:
      pixel5-08:
      pixel5-09:
      pixel5-10:
      pixel5-11:
      pixel5-12:
      pixel5-13:
      pixel5-14:
      pixel5-15:
      pixel5-16:
      pixel5-17:
  pixel5-perf:
      pixel5-18:
      pixel5-19:
  pixel6-unit:
  pixel6-perf:
      pixel6-01:
      pixel6-02:
      pixel6-03:
      pixel6-04:
  s21-unit:
  s21-perf:
      s21-01:
