projects:
  defaults:
    os_type: ANDROID
    project_type: APPIUM_ANDROID_SERVER_SIDE
    application_file: relops-testdroid-sample-app.apk
    test_file: relops-empty-test.zip
    timeout: 0
    scheduler: SINGLE
    archivingStrategy: DAYS
    archivingItemCount: 7
    taskcluster_provisioner_id: proj-autophone
    additional_parameters:
      bitbar_cloud_url: https://mozilla.testdroid.com
      DOCKER_IMAGE_VERSION: 20221010T124603
      TC_WORKER_CONF: gecko-t-ap
  # generic-worker
  mozilla-gw-unittest-p2:
    device_group_name: pixel2-unit-2
    device_model: pixel2
    framework_name: mozilla-usb
    description: Mozilla Unit tests for Pixel2 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-p2
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-p2
  mozilla-gw-perftest-p2:
    device_group_name: pixel2-perf-2
    device_model: pixel2
    framework_name: mozilla-usb
    description: Mozilla Performance tests for Pixel2 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-p2
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-p2
  mozilla-gw-unittest-p5:
    device_group_name: pixel5-unit
    device_model: pixel5
    framework_name: mozilla-usb
    description: Mozilla Unit tests for Pixel5 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-p5
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-p5
  mozilla-gw-perftest-p5:
    device_group_name: pixel5-perf
    device_model: pixel5
    framework_name: mozilla-usb
    description: Mozilla Performance tests for Pixel5 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-p5
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-p5
  # mozilla-gw-perftest-g5:
  #   device_group_name: motog5-perf-2
  #   device_model: motog5
  #   framework_name: mozilla-usb
  #   description: Mozilla Performance tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-g5
  # mozilla-gw-batttest-p2:
  #   device_group_name: pixel2-batt-2
  #   device_model: pixel2
  #   framework_name: mozilla-tcp
  #   description: Mozilla Battery tests for Pixel2 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-batt-p2
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-batt-p2
  # mozilla-gw-batttest-g5:
  #   device_group_name: motog5-batt-2
  #   device_model: motog5
  #   framework_name: mozilla-tcp
  #   description: Mozilla Battery tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-batt-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-batt-g5
  # mozilla-gw-unittest-g5:
  #   device_group_name: motog5-unit-2
  #   device_model: motog5
  #   framework_name: mozilla-usb
  #   description: Mozilla Unit tests for MotoG5 (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-g5
  # mozilla-gw-unittest-s7:
  #   device_group_name: s7-unit
  #   device_model: s7
  #   framework_name: mozilla-usb
  #   description: Mozilla Unit tests for S7Galaxy (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-s7
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-s7
  # mozilla-gw-perftest-s7:
  #   device_group_name: s7-perf
  #   device_model: s7
  #   framework_name: mozilla-usb
  #   description: Mozilla Performance tests for S7Galaxy (using generic-worker)
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-s7
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-s7
  mozilla-gw-unittest-a51:
    device_group_name: a51-unit
    device_model: a51
    framework_name: mozilla-usb
    description: Mozilla Unit tests for A51 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-unit-a51
      TC_WORKER_TYPE: gecko-t-bitbar-gw-unit-a51
  mozilla-gw-perftest-a51:
    device_group_name: a51-perf
    device_model: a51
    framework_name: mozilla-usb
    description: Mozilla Performance tests for A51 (using generic-worker)
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-bitbar-perf-a51
      TC_WORKER_TYPE: gecko-t-bitbar-gw-perf-a51
  # used for building new docker images
  # mozilla-docker-build:
  #   device_group_name: motog4-docker-builder-2
  #   device_model: motog4
  #   framework_name: Docker image build
  #   description: Mozilla Docker image build
  #   test_file: mozilla-docker-20201102T161546.zip
  #   # app file is defaulted
  #   additional_parameters:
  #     DOCKER_IMAGE_VERSION: 20201102T161546
  # used for testing new docker images
  mozilla-gw-test-1:
    device_group_name: test-1
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-1
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-1
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20211130T120953
  mozilla-gw-test-2:
    device_group_name: test-2
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-2
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-2
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20211130T120953
  mozilla-gw-test-3:
    device_group_name: test-3
    framework_name: mozilla-usb
    description: used for testing new images, devices, operating systems
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-3
      TC_WORKER_TYPE: gecko-t-bitbar-gw-test-3
      # replace with version to test
      DOCKER_IMAGE_VERSION: 20220322T145503
  # mozilla-docker-image-test:
  #   device_group_name: motog5-test
  #   framework_name: mozilla-usb
  #   description: Mozilla Docker image test
  #   additional_parameters:
  #     TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-test-g5
  #     TC_WORKER_TYPE: gecko-t-bitbar-gw-test-g5
  #     # replace with version to test
  #     DOCKER_IMAGE_VERSION: 20200326T142021
# devices hooked up to battery hubs
#   - pixel2-34, pixel2-35. motog5-08, motog5-15.
device_groups:
  motog4-docker-builder-2:
    Docker Builder:
  motog5-perf:
  motog5-perf-2:
    # disabled to draw down cluster to 2020 contract sizes (27 g5, 48 p2)
    # motog5-01:
    # motog5-02:  # replaces 5-39, bad also
    # motog5-03:
    # motog5-04:
    # motog5-05:
    # motog5-06:
    # motog5-07:  # replaces 5-31, disabled for a51
    # motog5-08:
    # motog5-09:
    # motog5-10:
    # motog5-11:
    # motog5-12:
    # motog5-13:
    # disabled to add 4 s7g
    # motog5-14:
    # motog5-15:
    # motog5-16:
    # motog5-17:  # replaces 5-02, disabled for a51
    # motog5-18:  # disabled for a51
    # motog5-19:  # disabled for a51
    # motog5-20:  # disabled for a51
    # motog5-21:  # disabled for a51
    # motog5-22:  # disabled for a51
    # motog5-23:  # disabled for a51
    # motog5-24:  # disabled for a51
    # motog5-25:  # disabled for a51
    # motog5-26:  # 7/13/22: disabled for a51
    # motog5-27:  # 7/13/22: disabled for a51
    # motog5-28:  # 7/13/22: disabled for a51
    # motog5-29:  # 7/13/22: disabled for a51
    # motog5-30:  # 7/13/22: disabled for a51
    # motog5-31:  # bad device
    # motog5-32:  # 7/13/22: disabled for a51
    # motog5-33:  # disabled due to 2021 contract (and battery bloat)
    # motog5-34:  # disabled 8/9/22
    # motog5-35:  # disabled 8/9/22
    # motog5-36:  # 11/30/22: disabling all g5, not used any longer
    # motog5-37:  # 11/30/22: disabling all g5, not used any longer
    # motog5-39:  # bad device
  motog5-unit:
  motog5-unit-2:
  motog5-test:
  test-1:
    # motog5-38:  # 11/30/22: disabling all g5, not used any longer
  test-2:
    # motog5-40:  # disabled due to a51 device increases (3/29/22)
  test-3:
    # pixel2-60 has android 9.0 on it
    #pixel2-60: ## pulled 4/26/22
  a51-unit:
  a51-perf:
      a51-01:
      a51-02:
      a51-03:
      a51-04:
      a51-05:
      a51-06:
      a51-07:
      a51-08:
      a51-09:
      a51-10:
      a51-11:
      a51-12:
      a51-13:
      a51-14:
      a51-15:
      a51-16:
      a51-17:
      a51-18:
      a51-19:
      a51-20:
      a51-21:
      a51-22:
      a51-23:
      a51-24:
      a51-25:
      a51-26:
      a51-27:
  pixel5-unit:
      pixel5-01:
      pixel5-02:
      pixel5-03:
      pixel5-04:
      pixel5-05:
      pixel5-06:
      pixel5-07:
      pixel5-08:
      pixel5-09:
      pixel5-10:
      pixel5-11:
      pixel5-12:
      pixel5-13:
      pixel5-14:
      pixel5-15:
      pixel5-16:
      pixel5-17:
  pixel5-perf:
      pixel5-18:
      pixel5-19:
  motog5-batt:
  motog5-batt-2:
  pixel2-unit:
  pixel2-unit-2:
    # pixel2-01:  # 1/10/23: p2 drawdown
    # pixel2-02:  # 1/10/23: p2 drawdown
    # pixel2-03:
    # pixel2-04:
    # pixel2-05:
    # pixel2-06:
    # pixel2-07:
    # pixel2-08:  # 1/10/23: p2 drawdown
    # pixel2-09:
    # pixel2-10:
    # pixel2-11:  # 1/10/23: p2 drawdown
    # pixel2-12:  # 1/10/23: p2 drawdown
    # pixel2-13:  # 1/10/23: p2 drawdown
    # pixel2-14:  # 1/10/23: p2 drawdown
    # pixel2-15:  # 1/10/23: p2 drawdown
    # pixel2-16:  # 7/14/22: failed device
    # pixel2-17:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-18:  # 7/17/22: failed device
    # pixel2-19:  # 7/14/22: failed device
    # pixel2-20:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-21:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-22:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-23:  # disabled due to 2021 contract (and battery bloat)
    # pixel2-24:  # disabled due to 2021 contract (and battery bloat)
    # pixel2-25:  # disabled due to 2021 contract (and battery bloat)
    # pixel2-26:  # 2/15/23: RELOPS-410: remove most p2
    pixel2-28:
    pixel2-29:
    pixel2-30:
  pixel2-perf:
  pixel2-perf-2:
    # pixel2-31:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-32:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-27:  # 7/14/22: failed device
    # pixel2-33:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-34:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-35:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-36:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-37:  # 10/7/22: bad device / battery issues
    # pixel2-38:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-39:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-40:  # 9/15/22: bad device
    # pixel2-41:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-42:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-43:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-44:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-45:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-46:  # 11/30/22: deactivated for phase 2 of p5
    # pixel2-47:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-48:  # 7/17/22: failed device
    # pixel2-49:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-50:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-51: # removed from cluster due to flakiness (hangs, turns off)
    # pixel2-52: # removed from cluster due to battery bloat
    # pixel2-53: # removed due to having issues
    # pixel2-54:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-55:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-56:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-57:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-58:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-59:  # 2/15/23: RELOPS-410: remove most p2
    # pixel2-60:  # lots of failures and on android 9 (vs 8)
  pixel2-batt:
  pixel2-batt-2:
  s7-unit:
  s7-perf:
    #s7-01:  # s7s pulled 4/26/22
    #s7-02:
    #s7-03:
    #s7-04:
